# -*- coding: utf-8 -*-
"""a4_practicaDeLimpiezaDeDatos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PaY_60ZhQKpvSr1c8Wu-5PnzldaeP74z
"""

import pandas as pd
import numpy as np

# 1. Cargar la base de datos
file_path = 'dirty_cafe_sales.csv'
df = pd.read_csv(file_path)

print("="*50)
print(" 1. INSPECCIÓN INICIAL DE LA BASE DE DATOS")
print("="*50)
print(f"Total de registros originales: {len(df)}")
print("\n--- Conteo de Nulos Originales ---")
print(df.isnull().sum())

# 2. Reemplazo de errores tipográficos por nulos reales
df.replace(['ERROR', 'UNKNOWN'], np.nan, inplace=True)

# 3. Conversión de Tipos de Datos Numéricos
numeric_cols = ['Quantity', 'Price Per Unit', 'Total Spent']
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# 4. Formateo de Fechas
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'], errors='coerce')

print("\n" + "="*50)
print(" 2. DETECCIÓN DE PROBLEMAS TRAS LA CONVERSIÓN")
print("="*50)
print("\n--- Nuevos Nulos (incluyendo 'ERROR'/'UNKNOWN' convertidos) ---")
print(df.isnull().sum())

print("\n--- Filas duplicadas ---")
duplicados = df.duplicated().sum()
print(f"Total de duplicados: {duplicados}")

# 5. Detección de Outliers (Valores atípicos) mediante IQR
print("\n--- Valores Atípicos (Método IQR) ---")
for col in numeric_cols:
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1
    outliers = ((df[col] < (q1 - 1.5 * iqr)) | (df[col] > (q3 + 1.5 * iqr))).sum()
    print(f"{col}: {outliers} atípicos detectados")

# ==========================================
# 6. LIMPIEZA Y TRANSFORMACIÓN DE LA BASE
# ==========================================
df_clean = df.copy()

# A. Eliminación de Duplicados
if duplicados > 0:
    df_clean = df_clean.drop_duplicates()

# B. Se calcula total spent al multiplicar cantidad y precio
condicion_recalculo = df_clean['Total Spent'].isnull() & df_clean['Quantity'].notnull() & df_clean['Price Per Unit'].notnull()
df_clean.loc[condicion_recalculo, 'Total Spent'] = df_clean['Quantity'] * df_clean['Price Per Unit']

# C. Imputación estadística para datos numéricos
# Usamos la mediana para Cantidad y Precio por Unidad
df_clean['Quantity'] = df_clean['Quantity'].fillna(df_clean['Quantity'].median())
df_clean['Price Per Unit'] = df_clean['Price Per Unit'].fillna(df_clean['Price Per Unit'].median())
# Recalculo de totales tras rellenar cantidad y precio de unidad en vacios
df_clean['Total Spent'] = df_clean['Total Spent'].fillna(df_clean['Quantity'] * df_clean['Price Per Unit'])

# D. Se rellenan variables categoricas con medias
categorical_cols = ['Item', 'Payment Method', 'Location']
for col in categorical_cols:
    # Rellenamos los vacíos con la moda (el valor más frecuente)
    moda = df_clean[col].mode()[0]
    df_clean[col] = df_clean[col].fillna(moda)

# E. Correccion de fechas (FForward / BBackward fill)
df_clean['Transaction Date'] = df_clean['Transaction Date'].ffill().bfill()

print("\n" + "="*50)
print(" 3. RESULTADO FINAL")
print("="*50)
print(df_clean.info())

# 7. Exportar la base limpia
export_name = 'cafe_sales_cleaned_final.csv'
df_clean.to_csv(export_name, index=False)
print(f"\n¡Base de datos limpia exportada exitosamente como '{export_name}'!")